name: Release
on:
  push:
    tags:
      - "*"

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: astral-sh/setup-uv@v5
      with:
        version: "0.6.x"
    - name: Bundle and create release
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        mkdir bundle/
        uv pip install --python-version 3.9 --python-platform linux --requirements pyproject.toml --target bundle/yt_dlp_plugins/
        rm -rf bundle/yt_dlp_plugins/*.dist-info bundle/yt_dlp_plugins/bin
        cp -ra yt_dlp_plugins bundle/
        (cd bundle/ && zip -9 --recurse-paths yt-dont-lock-p yt_dlp_plugins)

        version="$(uv tool run hatch version)"
        gh release create "${version}" --latest \
            --title "yt-dont-lock-p ${version}" \
            'bundle/yt-dont-lock-p.zip'
