name: Create release
on: [push]

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set variables
      id: set_variables
      run: |
        echo "::group::Variables"
        cat << EOF | tee -a "$GITHUB_OUTPUT"
        tag=$(git describe --tags --abbrev=0)
        version=v$(sed -n 's/^version\s*=\s*"\(.*\)"$/\1/p' pyproject.toml)
        EOF
        echo "::endgroup::"

    - name: Bundle and create release
      env:
        GH_TOKEN: ${{ github.token }}
        tag: ${{ steps.set_variables.outputs.tag }}
        version: ${{ steps.set_variables.outputs.version }}
      if: |
        env.tag != env.version
      run: |
        files=(*)

        git clone --branch latest-release -- https://github.com/fohrloop/wakepy wakepy/
        mkdir bundle/
        cp -rt bundle -- "${files[@]}"
        cp -r wakepy/wakepy bundle/yt_dlp_plugins/

        cd bundle/
        zip -9 --recurse-paths yt-dont-lock-p *
        gh release create "${version}" --latest \
          --title "yt-dont-lock-p ${version}" \
          'yt-dont-lock-p.zip'
