name: Run tests
on: [push, pull_request]

jobs:
  tests:
    name: Lint / Format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v5
      with:
        version: "0.6.x"
    - name: Run static analysis
      run: uv tool run hatch fmt --check
