name: Run tests
on: [push, pull_request]

jobs:
  tests:
    name: Lint / Format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
    - name: Install hatch
      run: pip install hatch
    - name: Run lint
      run: hatch run ci:lint
    - name: Run format
      run: hatch run ci:format
